import { useState } from "react";
import {
  AlertCircle,
  AlertTriangle,
  Bot,
  CheckCircle2,
  Clock,
  Compass,
  Layers,
  ListChecks,
  RotateCw,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDateTime } from "@/lib/format";
import { cn } from "@/lib/utils";
import type { AIManeuverAdvisory } from "@/types/aiAdvisory";

interface AiAdvisoryDetailProps {
  advisory: AIManeuverAdvisory;
  onRegenerate: () => Promise<unknown>;
  isRegenerating?: boolean;
}

export function AiAdvisoryDetail({
  advisory,
  onRegenerate,
  isRegenerating = false,
}: AiAdvisoryDetailProps) {
  const { recommendation, modelUsed, updatedAt } = advisory;
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});

  const isSimulated =
    modelUsed.toLowerCase().includes("simulated") ||
    modelUsed.toLowerCase().includes("fallback") ||
    modelUsed.toLowerCase().includes("(advisory)");

  const toggleCheck = (idx: number) => {
    setCheckedItems((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  return (
    <div className="space-y-4 rounded-b-lg border-t border-border/80 bg-card/40 p-5 backdrop-blur-md">
      {/* Unmissable Simulation Warning Banner */}
      {isSimulated && (
        <div className="flex items-center gap-3 rounded-md border-2 border-amber-500/60 bg-amber-500/20 p-3.5 text-amber-200 shadow-sm animate-pulse">
          <AlertTriangle className="h-5 w-5 shrink-0 text-amber-400" />
          <div className="space-y-0.5">
            <p className="text-xs font-bold uppercase tracking-wider text-amber-300 flex items-center gap-1.5">
              <span>SIMULATED ADVISORY — NO LIVE AI MODEL CONFIGURED</span>
            </p>
            <p className="text-[11px] text-amber-200/90 leading-snug">
              This recommendation was generated by local deterministic astrodynamics heuristics because no live <span className="font-mono bg-black/40 px-1 py-0.5 rounded text-amber-100 font-semibold">ANTHROPIC_API_KEY</span> is set on the backend. This is NOT an Anthropic Claude response.
            </p>
          </div>
        </div>
      )}

      {/* Strategy Header Bar */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap items-center gap-2">
          <div
            className={cn(
              "flex items-center gap-1.5 rounded-md border px-3 py-1 text-xs font-semibold",
              isSimulated
                ? "border-amber-500/40 bg-amber-500/10 text-amber-300"
                : "border-purple-500/30 bg-purple-500/10 text-purple-300"
            )}
          >
            {isSimulated ? (
              <AlertTriangle className="h-3.5 w-3.5 text-amber-400" />
            ) : (
              <Sparkles className="h-3.5 w-3.5 text-purple-400" />
            )}
            <span>Strategy: {recommendation.maneuver_strategy}</span>
          </div>

          {isSimulated ? (
            <Badge className="border-amber-500/40 bg-amber-500/20 text-amber-300 font-mono text-[10px] font-bold">
              ⚠️ SIMULATED HEURISTIC MODE
            </Badge>
          ) : (
            <Badge className="border-purple-500/30 bg-purple-500/10 text-purple-300 font-mono text-[10px] font-medium gap-1">
              <Bot className="h-3 w-3 text-purple-400" />
              <span>Generated by Claude ({modelUsed})</span>
            </Badge>
          )}

          <Badge variant="outline" className="border-border/80 bg-background/50 text-[11px] text-muted-foreground">
            Updated {formatDateTime(updatedAt)}
          </Badge>
        </div>

        <Button
          size="sm"
          variant="outline"
          onClick={onRegenerate}
          disabled={isRegenerating}
          className="h-8 gap-1.5 text-xs font-medium border-border/80 hover:bg-secondary"
        >
          <RotateCw className={cn("h-3.5 w-3.5", isRegenerating && "animate-spin text-primary")} />
          {isRegenerating ? "Re-analyzing…" : "Regenerate Advisory"}
        </Button>
      </div>

      {/* Qualitative Risk Summary */}
      <div className="rounded-md border border-border/60 bg-secondary/30 p-3.5">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-foreground">
          <AlertCircle className="h-3.5 w-3.5 text-amber-400" />
          <span>Qualitative Encounter Assessment</span>
        </div>
        <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
          {recommendation.qualitative_risk_summary}
        </p>
      </div>

      {/* Two Column Grid: Rationale & Timing Window */}
      <div className="grid gap-3 sm:grid-cols-2">
        {/* Maneuver Physics & Direction */}
        <div className="rounded-md border border-border/60 bg-secondary/20 p-3.5 space-y-2">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-primary">
            <Compass className="h-3.5 w-3.5" />
            <span>Burn Direction & Astrodynamics Physics</span>
          </div>
          <p className="text-xs leading-relaxed text-muted-foreground">
            {recommendation.burn_direction_rationale}
          </p>
        </div>

        {/* Timing Window Guidance */}
        <div className="rounded-md border border-border/60 bg-secondary/20 p-3.5 space-y-2">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-cyan-400">
            <Clock className="h-3.5 w-3.5" />
            <span>Optimal Execution Timing Window</span>
          </div>
          <p className="text-xs leading-relaxed text-muted-foreground">
            {recommendation.optimal_timing_window}
          </p>
        </div>
      </div>

      {/* Operational Trade-offs & Considerations */}
      {recommendation.operational_tradeoffs && recommendation.operational_tradeoffs.length > 0 && (
        <div className="rounded-md border border-border/60 bg-secondary/20 p-3.5 space-y-2">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-amber-300">
            <Layers className="h-3.5 w-3.5" />
            <span>Operational Trade-offs & Astrodynamics Considerations</span>
          </div>
          <ul className="grid gap-1.5 sm:grid-cols-2">
            {recommendation.operational_tradeoffs.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 text-xs text-muted-foreground">
                <span className="mt-0.5 flex h-1.5 w-1.5 shrink-0 rounded-full bg-amber-400" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Flight Operations Verification Checklist */}
      {recommendation.verification_checklist && recommendation.verification_checklist.length > 0 && (
        <div className="rounded-md border border-border/60 bg-secondary/20 p-3.5 space-y-2.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-emerald-400">
              <ListChecks className="h-3.5 w-3.5" />
              <span>Flight Operations Pre-Burn Verification Checklist</span>
            </div>
            <span className="text-[11px] font-mono text-muted-foreground">
              {Object.values(checkedItems).filter(Boolean).length} of {recommendation.verification_checklist.length} verified
            </span>
          </div>
          <div className="space-y-1.5">
            {recommendation.verification_checklist.map((step, idx) => {
              const isDone = Boolean(checkedItems[idx]);
              return (
                <button
                  key={idx}
                  type="button"
                  onClick={() => toggleCheck(idx)}
                  className={cn(
                    "flex w-full items-start gap-2.5 rounded border p-2 text-left text-xs transition-colors",
                    isDone
                      ? "border-emerald-500/30 bg-emerald-500/10 text-foreground"
                      : "border-border/40 bg-card/30 text-muted-foreground hover:bg-secondary/40"
                  )}
                >
                  <CheckCircle2
                    className={cn(
                      "mt-0.5 h-3.5 w-3.5 shrink-0",
                      isDone ? "text-emerald-400" : "text-muted-foreground/50"
                    )}
                  />
                  <span className={cn(isDone && "line-through opacity-80")}>{step}</span>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Micro Disclaimer Footer */}
      <div className="flex items-center gap-2 pt-1 text-[11px] text-muted-foreground/70">
        <ShieldCheck className="h-3.5 w-3.5 text-muted-foreground/50" />
        <span>
          {recommendation.disclaimer}
        </span>
      </div>
    </div>
  );
}
