"""initial schema

Revision ID: dc6bb1d26626
Revises: 
Create Date: 2026-08-18 20:02:26.265273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6bb1d26626'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjunction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_satellite', sa.String(), nullable=False),
    sa.Column('primary_norad_id', sa.Integer(), nullable=False),
    sa.Column('secondary_object', sa.String(), nullable=False),
    sa.Column('secondary_norad_id', sa.Integer(), nullable=False),
    sa.Column('tca', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miss_distance_m', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('international_designator', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_org', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellites_norad_id'), 'satellites', ['norad_id'], unique=True)
    op.create_table('omm_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orbit_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=False),
    sa.Column('latitude_deg', sa.Float(), nullable=False),
    sa.Column('longitude_deg', sa.Float(), nullable=False),
    sa.Column('velocity_km_s', sa.Float(), nullable=False),
    sa.Column('inclination_deg', sa.Float(), nullable=False),
    sa.Column('period_minutes', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('raan_deg', sa.Float(), nullable=False),
    sa.Column('mean_anomaly_deg', sa.Float(), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id')
    )
    op.create_table('tle_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_id', sa.UUID(), nullable=False),
    sa.Column('line1', sa.String(), nullable=False),
    sa.Column('line2', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tle_records')
    op.drop_table('orbit_state')
    op.drop_table('omm_records')
    op.drop_index(op.f('ix_satellites_norad_id'), table_name='satellites')
    op.drop_table('satellites')
    op.drop_table('conjunction_events')
    # ### end Alembic commands ###
