import type { ConjunctionAlert } from "@/types/alert";

interface SimulatedItem {
  id: string;
  primarySatellite: string;
  primaryNoradId: number;
  secondaryObject: string;
  secondaryNoradId: number;
  daysOffset: number; // between 7.0 and 14.0 days
  missDistanceKm: number;
  relativeVelocityKmS: number;
  probability: number;
  riskLevel: "medium" | "low";
  screeningScope: "fleet_vs_catalog" | "fleet_vs_fleet";
  status: "open" | "monitoring";
}

const BASE_SIMULATED_DATA: SimulatedItem[] = [
  {
    id: "sim-alert-01",
    primarySatellite: "STARLINK-1007",
    primaryNoradId: 44713,
    secondaryObject: "COSMOS 1408 DEB",
    secondaryNoradId: 49863,
    daysOffset: 7.25,
    missDistanceKm: 8.45,
    relativeVelocityKmS: 13.8,
    probability: 3.4e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-02",
    primarySatellite: "ISS (ZARYA)",
    primaryNoradId: 25544,
    secondaryObject: "CZ-4B DEB",
    secondaryNoradId: 25942,
    daysOffset: 7.60,
    missDistanceKm: 34.20,
    relativeVelocityKmS: 11.2,
    probability: 4.1e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-03",
    primarySatellite: "NOAA-20",
    primaryNoradId: 43013,
    secondaryObject: "SL-16 R/B",
    secondaryNoradId: 22285,
    daysOffset: 8.15,
    missDistanceKm: 11.35,
    relativeVelocityKmS: 14.1,
    probability: 1.9e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-04",
    primarySatellite: "ONEWEB-0120",
    primaryNoradId: 45145,
    secondaryObject: "FENGYUN 1C DEB",
    secondaryNoradId: 29657,
    daysOffset: 8.50,
    missDistanceKm: 41.50,
    relativeVelocityKmS: 12.6,
    probability: 2.2e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-05",
    primarySatellite: "SENTINEL-6A",
    primaryNoradId: 46984,
    secondaryObject: "THOR ABLESTAR DEB",
    secondaryNoradId: 224,
    daysOffset: 8.90,
    missDistanceKm: 15.80,
    relativeVelocityKmS: 9.8,
    probability: 8.6e-6,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-06",
    primarySatellite: "HUBBLE ST",
    primaryNoradId: 20580,
    secondaryObject: "DELTA 1 DEB",
    secondaryNoradId: 14812,
    daysOffset: 9.30,
    missDistanceKm: 28.40,
    relativeVelocityKmS: 10.4,
    probability: 6.8e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-07",
    primarySatellite: "TERRA",
    primaryNoradId: 25994,
    secondaryObject: "IRIDIUM 33 DEB",
    secondaryNoradId: 33750,
    daysOffset: 9.75,
    missDistanceKm: 6.25,
    relativeVelocityKmS: 14.7,
    probability: 4.6e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-08",
    primarySatellite: "TIANGONG",
    primaryNoradId: 48274,
    secondaryObject: "CZ-2C DEB",
    secondaryNoradId: 40051,
    daysOffset: 10.10,
    missDistanceKm: 36.80,
    relativeVelocityKmS: 8.9,
    probability: 3.3e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-09",
    primarySatellite: "STARLINK-3011",
    primaryNoradId: 52758,
    secondaryObject: "YAOGAN-30 DEB",
    secondaryNoradId: 43232,
    daysOffset: 10.55,
    missDistanceKm: 13.90,
    relativeVelocityKmS: 12.1,
    probability: 1.4e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-10",
    primarySatellite: "AQUA",
    primaryNoradId: 27424,
    secondaryObject: "ARIANE 40 DEB",
    secondaryNoradId: 23561,
    daysOffset: 10.95,
    missDistanceKm: 45.10,
    relativeVelocityKmS: 11.5,
    probability: 1.6e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-11",
    primarySatellite: "LANDSAT-9",
    primaryNoradId: 49260,
    secondaryObject: "TITAN 3C DEB",
    secondaryNoradId: 3433,
    daysOffset: 11.35,
    missDistanceKm: 9.60,
    relativeVelocityKmS: 13.4,
    probability: 2.8e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-12",
    primarySatellite: "SWIFT",
    primaryNoradId: 28485,
    secondaryObject: "PEGASUS DEB",
    secondaryNoradId: 24027,
    daysOffset: 11.70,
    missDistanceKm: 32.10,
    relativeVelocityKmS: 9.3,
    probability: 4.9e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-13",
    primarySatellite: "ENVISAT",
    primaryNoradId: 27386,
    secondaryObject: "COSMOS 2251 DEB",
    secondaryNoradId: 33591,
    daysOffset: 12.10,
    missDistanceKm: 18.40,
    relativeVelocityKmS: 14.5,
    probability: 6.7e-6,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-14",
    primarySatellite: "RADARSAT-2",
    primaryNoradId: 32382,
    secondaryObject: "ATLAS CENTAUR DEB",
    secondaryNoradId: 19046,
    daysOffset: 12.45,
    missDistanceKm: 26.90,
    relativeVelocityKmS: 10.8,
    probability: 7.5e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-15",
    primarySatellite: "CRYOSAT-2",
    primaryNoradId: 36508,
    secondaryObject: "PSLV DEB",
    secondaryNoradId: 44105,
    daysOffset: 12.80,
    missDistanceKm: 21.70,
    relativeVelocityKmS: 11.9,
    probability: 5.4e-6,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-16",
    primarySatellite: "METOP-C",
    primaryNoradId: 43689,
    secondaryObject: "H-2A DEB",
    secondaryNoradId: 38341,
    daysOffset: 13.15,
    missDistanceKm: 38.60,
    relativeVelocityKmS: 13.0,
    probability: 2.9e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-17",
    primarySatellite: "GPM-CORE",
    primaryNoradId: 39574,
    secondaryObject: "BREEZE-M DEB",
    secondaryNoradId: 38753,
    daysOffset: 13.45,
    missDistanceKm: 7.80,
    relativeVelocityKmS: 14.2,
    probability: 3.7e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-18",
    primarySatellite: "JASON-3",
    primaryNoradId: 41240,
    secondaryObject: "DELTA 2 DEB",
    secondaryNoradId: 25862,
    daysOffset: 13.75,
    missDistanceKm: 47.30,
    relativeVelocityKmS: 8.7,
    probability: 1.2e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_catalog",
    status: "open",
  },
  {
    id: "sim-alert-19",
    primarySatellite: "ICESAT-2",
    primaryNoradId: 43613,
    secondaryObject: "THOR AGENA DEB",
    secondaryNoradId: 1344,
    daysOffset: 13.90,
    missDistanceKm: 12.40,
    relativeVelocityKmS: 12.3,
    probability: 1.6e-5,
    riskLevel: "medium",
    screeningScope: "fleet_vs_catalog",
    status: "monitoring",
  },
  {
    id: "sim-alert-20",
    primarySatellite: "STARLINK-1007",
    primaryNoradId: 44713,
    secondaryObject: "TIANGONG",
    secondaryNoradId: 48274,
    daysOffset: 14.00,
    missDistanceKm: 29.50,
    relativeVelocityKmS: 7.8,
    probability: 6.2e-7,
    riskLevel: "low",
    screeningScope: "fleet_vs_fleet",
    status: "open",
  },
];

/**
 * Dynamically produces 20 simulated collision alerts with dates
 * strictly between 7.0 and 14.0 days into the future.
 */
export function generateSimulatedAlerts(): ConjunctionAlert[] {
  const now = Date.now();
  const createdDate = new Date(now - 3600_000 * 2).toISOString();

  return BASE_SIMULATED_DATA.map((item) => {
    const tcaTimestamp = now + item.daysOffset * 86_400_000;
    const tcaIso = new Date(tcaTimestamp).toISOString();

    return {
      id: item.id,
      primarySatellite: item.primarySatellite,
      primaryNoradId: item.primaryNoradId,
      secondaryObject: item.secondaryObject,
      secondaryNoradId: item.secondaryNoradId,
      tca: tcaIso,
      missDistanceKm: item.missDistanceKm,
      missDistanceM: item.missDistanceKm * 1000.0,
      relativeVelocityKmS: item.relativeVelocityKmS,
      probability: item.probability,
      riskLevel: item.riskLevel,
      status: item.status,
      screeningScope: item.screeningScope,
      detectedBy: "satguard_simulated",
      createdAt: createdDate,
      computedAt: createdDate,
    };
  });
}
